# Generated by Django 5.2 on 2025-04-17 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_produto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'managed': False},
        ),
    ]
