# Generated by Django 5.2 on 2025-04-17 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque', models.IntegerField()),
                ('idfornecedor', models.ForeignKey(db_column='id_fornecedor', on_delete=django.db.models.deletion.CASCADE, to='vendas.fornecedor')),
            ],
        ),
    ]
