# Generated by Django 5.2 on 2025-04-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_alter_fornecedor_options_alter_produto_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itens_Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
            ],
            options={
                'db_table': 'itens_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id_pagamento', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pagamento', models.CharField(choices=[('Cartão de Crédito', 'Cartão de Crédito'), ('PIX', 'PIX'), ('Boleto', 'Boleto'), ('Dinheiro', 'Dinheiro')], max_length=20)),
                ('status_pagamento', models.CharField(choices=[('Pendente', 'Pendente'), ('Pago', 'Pago'), ('Cancelado', 'Cancelado')], max_length=10)),
            ],
            options={
                'db_table': 'pagamento',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='fornecedor',
            table='fornecedor',
        ),
        migrations.AlterModelTable(
            name='produto',
            table='produtos',
        ),
    ]
