# Generated by Django 5.2 on 2025-04-19 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_itens_pedido_pagamento_alter_fornecedor_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itens_pedido',
            options={},
        ),
    ]
