# Generated by Django 5.2 on 2025-04-19 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_alter_itens_pedido_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itens_pedido',
            options={'managed': False},
        ),
    ]
